export const COMPANIES_URL: string = '/companies'
export const SEARCH_APP_URL: string = '/search_app/api/v1/'
export const BOOKMARKS_URL: string = '/bookmarks/api/v1/company_bookmarks'
export const TRACKING_EVENTS_URL: string = '/octopus/api/events'
export const TRACKING_PAGES_URL: string = '/octopus/api/pages'
export const SWITCHER_URL: string = '/internal_api/v1/flags?only='
